version: 2.1

branch-filters: &branch-filters
  filters:
    branches:
      only:
        - master

defaults: &defaults
  working_directory: ~/ci
  docker:
    - image: circleci/node:14

jobs:
  build-and-test:
    <<: *defaults  
    steps:
      - checkout:
          path: ~/ci

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

      - run:
          name: Compile
          command: |
            npm run compile

      - run:
          name: Run tests
          command: |
            npm run test

      - persist_to_workspace:
          root: ~/ci
          paths: 
            - .

  publish:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/ci

      - run:
          name: Publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/ci/.npmrc
            npm publish --access=public

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-test:
          context: npm-publish
      - publish:
          requires:
            - build-and-test
          context: npm-publish
          <<: *branch-filters
