version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:14

    working_directory: ~/ci

    steps:
      - checkout:
          path: ~/ci

      - restore_cache:
        keys:
          - dependencies-cache-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
        paths:
          - node_modules
        key: dependencies-cache-{{ checksum "package.json" }}

      - run:
          name: Compile
          command: |
            npm run compile

      - run:
          name: Run tests
          command: |
            npm run test

      - run:
          name: Publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/ci/.npmrc
            npm publish

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-test:
          context: npm-publish