---
# Source: icarus/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: "RELEASE_NAME-backend"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: "RELEASE_NAME-backend"
---
# Source: icarus/templates/deployments.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "RELEASE_NAME-backend"
  namespace: default
  labels:
    name: "RELEASE_NAME-backend"
spec:
  replicas: 3
  selector:
    matchLabels:
      name: "RELEASE_NAME-backend"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: "RELEASE_NAME-backend"
    spec:
      containers:
        - name: "worker"
          image: "pennlabs/penn-courses-backend:123456IMAGETAG"
          imagePullPolicy: IfNotPresent
          command:
            - "celery"
            - "worker"
            - "-A"
            - "PennCourses"
            - "-Q"
            - "alerts,celery"
            - "-linfo"
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: penn-courses
          env:
            - name: "DJANGO_SETTINGS_MODULE"
              value: "PennCourses.settings.production"
            - name: "PORT"
              value: "80"
---
# Source: icarus/templates/crontabs.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "RELEASE_NAME-load-courses"
  namespace: default
  labels:
    name: "RELEASE_NAME-load-courses"
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: "worker"
              image: pennlabs/penn-courses-backend:123456IMAGETAG
              imagePullPolicy: IfNotPresent
              command:
                - "python"
                - "manage.py"
                - "registrarimport"
              envFrom:
                - secretRef:
                    name: penn-courses
---
# Source: icarus/templates/crontabs.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "RELEASE_NAME-report-stats"
  namespace: default
  labels:
    name: "RELEASE_NAME-report-stats"
spec:
  schedule: "0 20 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: "worker"
              image: pennlabs/penn-courses-backend:123456IMAGETAG
              imagePullPolicy: IfNotPresent
              command:
                - "python"
                - "manage.py"
                - "alertstats"
                - "1"
                - "--slack"
              envFrom:
                - secretRef:
                    name: penn-courses
---
# Source: icarus/templates/ingresses.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE_NAME-backend
  namespace: default
spec:
  rules:
    - host: "penncourseplan.com"
      http:
        paths:
          - path: "/api"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/admin"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/accounts"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/assets"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
    - host: "penncoursealert.com"
      http:
        paths:
          - path: "/api"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/admin"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/accounts"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/assets"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/webhook"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
    - host: "review.penncourses.org"
      http:
        paths:
          - path: "/api"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/admin"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/accounts"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
          - path: "/assets"
            backend:
              serviceName: RELEASE_NAME-backend
              servicePort: 80
  tls:
    - hosts:
        - "penncourseplan.com"
      secretName: penncourseplan-com-tls
    - hosts:
        - "penncoursealert.com"
      secretName: penncoursealert-com-tls
    - hosts:
        - "review.penncourses.org"
      secretName: penncourses-org-tls
---
# Source: icarus/templates/certificates.yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: penncourseplan-com
  annotations:
    "helm.sh/resource-policy": keep
spec:
  secretName: penncourseplan-com-tls
  dnsNames:
    - "penncourseplan.com"
    - "*.penncourseplan.com"
  issuerRef:
    name: wildcard-letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
# Source: icarus/templates/certificates.yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: penncoursealert-com
  annotations:
    "helm.sh/resource-policy": keep
spec:
  secretName: penncoursealert-com-tls
  dnsNames:
    - "penncoursealert.com"
    - "*.penncoursealert.com"
  issuerRef:
    name: wildcard-letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
# Source: icarus/templates/certificates.yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: penncourses-org
  annotations:
    "helm.sh/resource-policy": keep
spec:
  secretName: penncourses-org-tls
  dnsNames:
    - "penncourses.org"
    - "*.penncourses.org"
  issuerRef:
    name: wildcard-letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
